name = "RelDist"
uuid = "07a87324-01b3-42e0-b1df-e58c716aec90"
version = "0.1.0"
authors = ["Sigurd Hofsmo Jakobsen <sigurd.jakobsen@sintef.no>"]

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Configurations = "5218b696-f38b-4ac9-8b61-a12ec717816d"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataFramesMeta = "1313f7d8-7da2-5740-9ea0-a2ca25f37964"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Debugger = "31a5f54b-26ea-5ae9-a837-f05ce5417438"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
GraphPlot = "a2cc645c-3eea-5389-862e-a155d0052231"
GraphRecipes = "bd48cda9-67a9-57be-86fa-5b3c104eda73"
GraphViz = "f526b714-d49f-11e8-06ff-31ed36ee7ee0"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
MetaGraphs = "626554b9-1ddb-594c-aa3c-2596fe9399a5"
MetaGraphsNext = "fa8bd995-216d-47f1-8a91-f3b68fbeb377"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Query = "1a8c2f83-1ff3-5112-b086-8aa67b057ba1"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SintPowerCase = "dcf425a8-86bf-4135-b17a-04ddca2f3b37"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TikzGraphs = "b4f28e30-c73f-5eaf-a395-8a9db949a742"
TikzPictures = "37f6aa50-8035-52d0-81c2-5a1d08754b2d"
TimeZones = "f269a46b-ccf7-5d73-abea-4c690281aa53"
